### ISSUE TITLE
Home Assistant integration WARNING:  Manually configured MQTT sensor(s) found under platform key 'sensor'

### ISSUE THREAD

**Issue by gremms1** [theoracle09/Weather-Station#4]
Hi,

Great project and write-up. I tried to replicate it, and for the most part got it to work. I'm failing at the Home Assistant integration, however. Got the following Warning in the logs:
"Manually configured MQTT sensor(s) found under platform key 'sensor', please move to the mqtt integration key, see https://www.home-assistant.io/integrations/sensor.mqtt/#new_format"

Being not very familiar with Home Assistant yet I tried to get it to work, but failed. Hope you can help me out.
Cheers

**Comment by theoracle09** [comment]
Hi there, thanks for bringing this to my attention. It looks like since I created the original "How To", Home Assistant has updated the way it handles MQTT integrations. I've updated it on my end so I know it's working and will update the instructions on the main page sometime today. In the meantime, here's what you need to know: 

I like to have new files for configuration.yaml entries, as it separates the code into 'modular' files I can read and understand better. If you're the same, go to your configuration.yaml and type the following:

`mqtt: !include mqtt.yaml`

Then create a new file in the same folder that your configuration.yaml file is in and name it `mqtt.yaml`. 

Inside mqtt.yaml, this is where you'll create the sensor for the main weather station payload, along with any other MQTT sensors you may have/need. Paste this in your newly created mqtt.yaml file:

```
sensor:
  - name: "Weather Station"
    state_topic: "raspberry/ws/status"
    json_attributes_topic: "raspberry/ws/sensors"
```

The state_topic and the json_attributes_topic need to match exactly what you have in weather_station.py on the pi itself. If those topics don't match, Home Assistant won't be able to 'hear' the raspi when it broadcasts the sensor data. Think of topics as channels: if Home Assistant is listening on the wrong channel it won't receive the message.

That should remove the warning and then you should see the sensor.weather_station populate with the readings from the pi. After that you can still use the sensor template as that's not affected by MQTT, if that's what you're going for.

**Comment by theoracle09** [comment]
Readme is updated via commit e507cebebc029ed0848555cf9ca84ae427dd9bea.
